name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME}}:latest"
      
    - name: Log into Docker registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push to Docker registry
      run: |
        version=$(cat VERSION)
        docker tag "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME}}:latest" "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME}}:${version}"
        docker push "${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME}}:${version}"
