name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME
      
    - name: Log into Docker registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.pkg.github.com -u ${{ $DOCKER_USER }} --password-stdin

    - name: Push to Docker registry
      run: |
        $VERSION=$(echo VERSION)
        docker tag $DOCKER_IMAGE_NAME $VERSION
        docker push ${DOCKER_USER}/${DOCKER_REPO}/$VERSION